name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev tk-dev libdb5.3-dev libexpat1-dev libmpdec-dev
          pip3 install --upgrade pip
          pip3 install buildozer Cython==0.29.33

      - name: Build with Buildozer
        run: |
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: bin/*.apk
